App\Entity\Catalog:
  type: entity
  repositoryClass: AppBundle\Repository\CatalogRepository
  table: catalog
  id:
    id:
      type: integer
      length: 10
      unique: true
      nullable: false
      id: true
      options:
        unsigned: true
      generator:
        strategy: IDENTITY
  oneToMany:
    products:
      targetEntity: App\Entity\Product
      mappedBy: category
  fields:
    name:
      type: string
      length: 200
    description:
      type: string
      length: 200
