Acme\StoreBundle\Entity\Product:
  type: entity
  table: product
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  manyToOne:
    catalog:
      targetEntity: App\Entity\Catalog
      inversedBy: products
      joinColumn:
        nullable: false
    manyToMany:
      productFilters:
        targetEntity: AppBundle\Entity\ProductFilters
        mappedBy: products
        joinColumn:
          name: product_id
          nullable: true
          referencedColumnName: id
          onDelete: CASCADE
  fields:
    name:
      type: string
      length: 200
    price:
      type: integer
      length: 200
    description:
      type: string
      length: 200
    code:
      type: string
      length: 200
    catalogId:
      type: integer
      length: 200
