Acme\StoreBundle\Entity\Product:
  type: entity
  table: product
  id:
    id:
      type: integer
        length: 10
        unique: true
        nullable: false
        id: true
        options:
          unsigned: true
        generator:
          strategy: IDENTITY
  manyToOne:
    catalog:
      targetEntity: App\Entity\Catalog
      mappedBy: catalog
      joinColumn:
        name: catalog_id
        nullable: true
        referencedColumnName: id
        onDelete: CASCADE
    manyToMany:
      productFilters:
        targetEntity: AppBundle\Entity\ProductFilters
        mappedBy: products
        joinColumn:
          name: catalog_id
          nullable: true
          referencedColumnName: id
          onDelete: CASCADE
  fields:
    name:
      type: string
      length: 200
    price:
      type: integer
      length: 200
    description:
      type: string
      length: 200
    code:
      type: int
      length: 200
    catalogId:
      type: integer
      length: 200
