Acme\StoreBundle\Entity\Product:
  type: entity
  table: product
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    product_id:
      type: string
      length: 200
    filterGroupCode:
      type: string
      length: 200
    brand:
      type: string
      length: 200