Acme\StoreBundle\Entity\Product:
  type: entity
  table: product
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 200
    price:
      type: integer
      length: 200
    description:
      type: string
      length: 200
    code:
      type: string
      length: 200
    catalogId:
      type: integer
      length: 200
