#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_lucky_number:
  path: /lucky/number
  controller: App\Controller\LuckyController::number

api_index:
  path: /index
  controller: App\Controller\ProductController::index

api_create_product:
  path: /create/product
  controller: App\Controller\ProductController::createProduct

api_show:
  controller: App\Controller\ProductController::showAction
  path: /show

api_update:
  path: /update
  controller: App\Controller\ProductController::updateAction

api_product_delete:
  path: /product/delete
  controller: App\Controller\ProductController::deleteAction
  methods: [GET]

api_product_filter_list:
  path: /filter/list
  controller: App\Controller\ProductController::filtersProductList
  methods: [GET]
